#!/bin/bash

# exclude some useless hidden directories, but not all.
# in particular, include *files* directly inside .git, .git/hooks and .git/info
command find -L $@ \
    -mindepth 1 \
    \( -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \
       -o -path '*.git/*' ! -path '*/.git/info' ! -path '*/.git/hooks' -a -type d \
       -o -name 'node_modules' \
       -o -path '*/codility/frontend_v2' \
       -o -path '*/codility/tasks' \
       -o -path '*/deployment/env3' \
       -o -path '*/vendor/cookbooks' \
       -o -path '*/build/mkdocs.venv' \
       -o -path '*/vendor/bundle' \
       -o -path '*/.local/share/Zeal' \
       -o -path '*/.local/share/Trash' \
       -o -path '*/.vim/plugged' \
       -o -path '*/.config/google-chrome' \
       -o -name '.npm' \
       -o -name '.cache' \
       -o -name '.chefdk' \
       -o -name 'site-packages' \
    \) -prune \
    -o -print \
    2> >(grep -v "Permission denied")
