#!/bin/bash

# exclude directories with lots of uninteresting stuff (some hidden, some not).
# Also filters out "permission denied" errors, as they are usually not helpful.

# find requires option for symlink handling to be at the beginning
if [ "$1" = "-H" -o "$1" = "-L" -o "$1" = "-P" ]; then
  FIND_SYMLINK_OPTS="$1"
  shift
fi

# separate paths from options
for arg in $@; do
  if [ -e $arg ]; then
    FIND_PATHS="$FIND_PATHS $arg"
    shift
  else
    break
  fi
done

# hacky support for -print0 option (doesn't work with complex expressions)
if [[ "$@" == *-print0* ]]; then
  PRINT_MTD="-print0"
  FIND_OPTS="${@//-print0}"
else
  PRINT_MTD="-print"
  FIND_OPTS="$@"
fi

command find $FIND_SYMLINK_OPTS $FIND_PATHS \
    -mindepth 1 \
    \( -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \
       -o -name '.git' \
       -o -name 'node_modules' \
       -o -name 'python_modules' \
       -o -path '*venv*/lib' \
       -o -path '*/deployment/env3' \
       -o -path '*/vendor/cookbooks' \
       -o -path '*/build/mkdocs.venv' \
       -o -path '*/vendor/bundle' \
       -o -path '*/.local/share/Zeal' \
       -o -path '*/.local/share/Trash' \
       -o -path '*/.vim/plugged' \
       -o -path '*/.terraform/modules' \
       -o -path '*/.terraform/plugins' \
       -o -path '*/terraform.*.backup' \
       -o -path '*/.config/google-chrome' \
       -o -path '/usr/share/icons' \
       -o -path '/usr/share/locale' \
       -o -path '/usr/src/linux-headers-*' \
       -o -path '/opt/chefdk/embedded/lib/ruby/gems' \
       -o -name '.npm' \
       -o -name '.cache' \
       -o -name '.chefdk' \
       -o -name '.berkshelf' \
       -o -name 'site-packages' \
    \) -prune \
    -o $FIND_OPTS $PRINT_MTD \
    2> >(grep -v "Permission denied")
