# defaults that apply to all vagrant boxes

$path = "#{ENV['HOME']}/.config/ansible-system-setup/provision-vagrant-vms.yml"

Vagrant.configure(2) do |config|
    config.vm.provision "ansible" do |ans|
        ans.playbook = $path
    end
end

